import { SITE } from '@/lib/site';

/**
 * Header badge linking to the eval suite. The headline metrics table is
 * maintained in the README (auto-generated by CI — see U10/U12); this badge
 * just signals the suite exists and is one click away.
 */
export function EvalBadge() {
  return (
    <a
      href={SITE.evalUrl}
      target="_blank"
      rel="noreferrer"
      className="inline-flex items-center gap-1.5 rounded-full border border-accent/40 bg-accent/10 px-3 py-1 text-xs font-medium text-accent transition-colors hover:bg-accent/20"
      title="Inspect AI eval suite — runs in CI on every push to main"
    >
      <span aria-hidden>✓</span>
      Eval suite · Inspect AI
    </a>
  );
}
